/*
 *
 *  Copyright [ 2020 - 2024 ] Matthew Buckton
 *  Copyright [ 2024 - 2026 ] MapsMessaging B.V.
 *
 *  Licensed under the Apache License, Version 2.0 with the Commons Clause
 *  (the "License"); you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at:
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *      https://commonsclause.com/
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package io.mapsmessaging.tools.config.yaml;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import io.mapsmessaging.config.ConfigManager;
import io.mapsmessaging.dto.rest.config.BaseConfigDTO;
import io.mapsmessaging.license.FeatureManager;
import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class YamlWriterTest {

  @Test
  void writerAddsHeaderRendersRootAndRemovesNestedSchemaVersion() {
    TestConfig config = new TestConfig();
    config.setSchemaLoadingVersion(7);
    config.label = "maps";
    config.child = new ChildConfig();
    config.child.setSchemaLoadingVersion(9);
    config.child.value = "nested";

    String yaml = YamlWriter.toYaml(config, schema(), RenderMode.FULL);

    assertTrue(yaml.contains("# Generated by MapsMessaging"));
    assertTrue(yaml.contains("# DO NOT EDIT BY HAND UNLESS YOU KNOW WHAT YOU ARE DOING"));
    assertTrue(yaml.contains("TestConfig:"));
    assertTrue(yaml.contains("  schemaLoadingVersion: 7"));
    assertTrue(yaml.contains("  label: maps"));
    assertTrue(yaml.contains("  child:"));
    assertTrue(yaml.contains("    value: nested"));
    assertFalse(yaml.contains("schemaLoadingVersion: 9"));
  }

  @Test
  void minimalWriterOmitsUnsetOptionalField() {
    TestConfig config = new TestConfig();

    String yaml = YamlWriter.toYaml(config, schema(), RenderMode.MINIMAL);

    assertFalse(yaml.contains("label:"));
    assertFalse(yaml.contains("child:"));
  }

  private static JsonObject schema() {
    JsonObject root = type("object");
    JsonObject properties = new JsonObject();

    JsonObject version = type("integer");
    properties.add("schemaLoadingVersion", version);
    properties.add("label", type("string"));

    JsonObject child = type("object");
    JsonObject childProperties = new JsonObject();
    childProperties.add("schemaLoadingVersion", type("integer"));
    childProperties.add("value", type("string"));
    child.add("properties", childProperties);
    properties.add("child", child);

    root.add("properties", properties);

    JsonArray required = new JsonArray();
    required.add("schemaLoadingVersion");
    root.add("required", required);
    return root;
  }

  private static JsonObject type(String type) {
    JsonObject schema = new JsonObject();
    schema.addProperty("type", type);
    return schema;
  }

  static class TestConfig extends BaseConfigDTO implements ConfigManager {
    String label;
    ChildConfig child;

    @Override
    public ConfigManager load(FeatureManager featureManager) {
      return this;
    }

    @Override
    public void save() throws IOException {
    }

    @Override
    public String getName() {
      return "TestConfig";
    }
  }

  static class ChildConfig extends BaseConfigDTO {
    String value;
  }
}
