steps:
  - label: "maven: Build and Deploy LoRa device"
    command:
      - export JAVA_HOME=/usr/lib/jvm/zulu21
      - mvn -DskipTests=true clean compile -U
      - export PATH=$JAVA_HOME/bin:$PATH
      - cd src/main/cpp
      - chmod +x build.sh
      - ./build.sh
      - buildkite-agent artifact upload libLoRaChipDevice.so
    agents:
      queue: "raspberrypi_build_agent"
  - wait

  - trigger: "090-server-snapshot-build"

  - trigger: "090-server-ml-snapshot-build"

  - wait

  - trigger: "200-build-windows-installer"