steps:
  - label: "maven: Build and Deploy MAPS Server and Applications"
    command:
      - echo "Starting MAPS Release Cycle"
    agents:
      queue: "orchestration"
  - wait

  - trigger: "090-server-snapshot-build"

  - trigger: "090-server-ml-snapshot-build"

  - wait
  - trigger: "095-maps-apps-packaging"
  - trigger: "095-drone-build-and-package"
  - trigger: "100-server-3rd-party-extensions-snapshot"
  - trigger: "200-build-windows-installer"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - label: "110 Build Halos Maps Pi Image"
    trigger: "110-build-halos-maps-pi-image"
    async: true
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"