steps:
  - label: ":maven: Build and release to github"
    command:
        - export SONAR_TOKEN=$(buildkite-agent secret get SONAR_TOKEN)
        - export NVD_API_KEY=$(buildkite-agent secret get nvd_api_key)
        - wget https://github.com/Maps-Messaging/web-admin-client/releases/download/maps_web_client_1.0.1/webAdminClient.tgz
        - tar -xvzf ./webAdminClient.tgz
        - if [ ! -d "out" ]; then echo "'out' directory missing after extraction"; exit 1; fi
        - |
          set -euo pipefail

          cd "${BUILDKITE_BUILD_CHECKOUT_PATH:-.}"
          git rev-parse --is-inside-work-tree >/dev/null || { echo "Not a git repo"; pwd; ls -la; exit 1; }
          
          git fetch --prune --tags origin '+refs/heads/*:refs/remotes/origin/*'
          
          if git rev-parse --verify --quiet origin/main >/dev/null; then
            BASE_REF=origin/main
          elif git rev-parse --verify --quiet origin/master >/dev/null; then
            BASE_REF=origin/master
          else
            echo "No origin/main or origin/master"; git ls-remote --heads origin; exit 1
          fi
          
          MAIN_SHA="$(git rev-parse --verify "$BASE_REF")"
          DEV_SHA="$(git rev-parse --verify origin/development)"
        
          echo "Using range: $MAIN_SHA..$DEV_SHA ($BASE_REF vs origin/development)"
          release-notes --range "${MAIN_SHA}..${DEV_SHA}" --jira --out release-notes.md
        
        

        - chmod +x ./packaging/scripts/prepare_build.sh
        - ./packaging/scripts/prepare_build.sh
        - mvn -DskipTests=true clean deploy -U
        - chmod +x ./packaging/*.sh
        - ./packaging/github_release.sh $(buildkite-agent secret get GIT_HUB_TOKEN)
        - chmod +x ./packaging/scripts/*
        - ./packaging/scripts/build_deb_package.sh $(buildkite-agent secret get NEXUS_USER) $(buildkite-agent secret get NEXUS_PASSWORD) maps_apt_daily
        - ./packaging/scripts/build_rpm_package.sh $(buildkite-agent secret get NEXUS_USER) $(buildkite-agent secret get NEXUS_PASSWORD) maps_yum_snapshot
        - sudo ./packaging/docker_build_release.sh $(buildkite-agent secret get DOCKER_USER) $(buildkite-agent secret get DOCKER_PASSWORD
    env:
      SONAR_TOKEN: "${SONAR_TOKEN}"
      BUILDKITE_ANALYTICS_TOKEN: "$(buildkite-agent secret get serverBuildKiteAnaylytics)"

    agents:
      queue: "java_build_queue"

