steps:
  - label: ":windows: Build Windows installer"
    command:
      - cd ./packaging/windows
      - powershell -NoProfile -ExecutionPolicy Bypass -File .\windows_packager.ps1 "$(buildkite-agent secret get NEXUS_USER)" "$(buildkite-agent secret get NEXUS_PASSWORD)"
    agents:
      queue: "windowsBuild"
