steps:
  - label: ":maven: Build and release to github"
    command:
      - wget https://github.com/Maps-Messaging/web-admin-client/releases/download/maps_web_client_1.0.1/webAdminClient.tgz
      - tar -xvzf ./webAdminClient.tgz
      - if [ ! -d "out" ]; then echo "'out' directory missing after extraction"; exit 1; fi
      - chmod +x ./packaging/scripts/prepare_build.sh
      - ./packaging/scripts/prepare_build.sh
      - mvn -DskipTests=true clean package -U
      - chmod +x ./packaging/*.sh
      - ./packaging/github_release.sh $(buildkite-agent secret get GIT_HUB_TOKEN)
      - chmod +x ./packaging/scripts/*
      - sudo ./packaging/docker_build_release.sh "$(buildkite-agent secret get DOCKER_USER)" "$(buildkite-agent secret get DOCKER_PASSWORD)" "$(buildkite-agent secret get AWS_ECR_PASSWORD)"

    agents:
      queue: "java_build_queue"

