#!/bin/bash

#
# Copyright [ 2020 - 2024 ] [Matthew Buckton]
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

set -e

case "$1" in
  configure)
    # Create necessary directories
    mkdir -p /etc/message_daemon

    # Set permissions
    chown -R root:root /opt/message_daemon
    chmod -R 755 /opt/message_daemon/bin

    if [ ! -d /var/log/message-daemon ]; then
        mkdir -p /var/log/message-daemon
    fi
    if [ ! -f /var/log/message-daemon/message-daemon.log ]; then
        touch /var/log/message-daemon/message-daemon.log
    fi

   # Copy the environment file
    cp /opt/message_daemon/etc/message_daemon.env /etc/message_daemon/message_daemon.env
    cp /opt/message_daemon/etc/message_daemon.service   /usr/lib/systemd/system/message_daemon.service

    # Install the message-daemon command
    ln -sf /opt/message_daemon/bin/message_daemon /usr/local/bin/message-daemon
    ln -sf /opt/message_daemon/bin/mapsTop.sh /usr/local/bin/mapsTop

    # Enable and start the service
    systemctl enable message_daemon.service
    systemctl start message_daemon.service
  ;;
esac

#DEBHELPER#

exit 0
