#!/bin/bash
#
#
#  Copyright [ 2020 - 2024 ] Matthew Buckton
#  Copyright [ 2024 - 2025 ] MapsMessaging B.V.
#
#  Licensed under the Apache License, Version 2.0 with the Commons Clause
#  (the "License"); you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at:
#
#      http://www.apache.org/licenses/LICENSE-2.0
#      https://commonsclause.com/
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

set -e

# Check if group exists, create if it doesn't
if ! getent group mapsmessaging >/dev/null; then
    addgroup --system mapsmessaging
fi

# Check if user exists, create if it doesn't
if ! getent passwd mapsmessaging >/dev/null; then
    adduser --system --ingroup mapsmessaging --home /opt/maps --shell /usr/sbin/nologin --disabled-login --gecos "Maps Messaging Server User" mapsmessaging
fi

exit 0
