#!/bin/bash

#
# Copyright [ 2020 - 2024 ] [Matthew Buckton]
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

set -e

case "$1" in
  remove|purge)
    # Stop and disable the service
    systemctl stop message_daemon.service
    systemctl disable message_daemon.service

    # Remove the symlink
    rm -f /usr/local/bin/message-daemon

    # Remove the environment file
    rm -f /etc/message_daemon/message_daemon.env
  ;;
esac

#DEBHELPER#

exit 0
