/*
 *
 *  Copyright [ 2020 - 2024 ] Matthew Buckton
 *  Copyright [ 2024 - 2025 ] MapsMessaging B.V.
 *
 *  Licensed under the Apache License, Version 2.0 with the Commons Clause
 *  (the "License"); you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at:
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *      https://commonsclause.com/
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package io.mapsmessaging.dto.rest.config.protocol.impl;

import io.mapsmessaging.dto.rest.config.protocol.ProtocolConfigDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@EqualsAndHashCode(callSuper = true)
@NoArgsConstructor
@Schema(description = "Inmarsat Protocol Configuration DTO")
public class InmarsatDTO extends ProtocolConfigDTO {

  @Schema(description = "Inmarsat API base URL, including version path (e.g. https://api.inmarsat.com/api/v1/)")
  protected String baseUrl;

  @Schema(description = "Client ID generated by Inmarsat for API access")
  protected String clientId;

  @Schema(description = "Client secret generated by Inmarsat for API access")
  protected String clientSecret;

  @Schema(description = "Interval in seconds between polling the Inmarsat API for incoming messages")
  protected int pollInterval;

  @Schema(description = "HTTP request timeout in seconds")
  protected int httpRequestTimeout;

  @Schema(description = "List of mailboxes to poll for messages")
  protected List<MailboxConfig> mailboxes;

  @Data
  @NoArgsConstructor
  @Schema(description = "Mailbox configuration for Inmarsat")
  public static class MailboxConfig {
    @Schema(description = "Mailbox ID")
    private String id;

    @Schema(description = "Mailbox password")
    private String password;
  }
}
