/*
 * Copyright [ 2024 - 2026 ] MapsMessaging B.V.
 * Licensed under the Apache License, Version 2.0 with the Commons Clause.
 */
package io.mapsmessaging.network.protocol.impl.mqtt_sn.v2_0.protection;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.InputStream;
import java.util.HexFormat;
import javax.crypto.spec.SecretKeySpec;
import org.junit.jupiter.api.Test;

/** Byte-for-byte expected output generated by independent Java/Python/C client providers. */
class MqttSn2ClientProtectionVectorsTest {
  @Test
  void everyStandardSchemeMatchesReferenceClientProvider() throws Exception {
    try (InputStream input = getClass().getResourceAsStream(
        "/mqtt_sn2/client-protection-provider-vectors.json")) {
      assertNotNull(input);
      JsonNode data = new ObjectMapper().readTree(input);
      byte[] prefix = HexFormat.of().parseHex(data.get("authenticatedPrefix").asText());
      byte[] plaintext = HexFormat.of().parseHex(data.get("plaintext").asText());
      MqttSn2CryptoProviders providers = new MqttSn2CryptoProviders();
      int checked = 0;
      for (JsonNode vector : data.get("vectors")) {
        int scheme = Integer.parseInt(vector.get("scheme").asText(), 16);
        var provider = providers.require(scheme);
        byte[] keyBytes = HexFormat.of().parseHex(vector.get("key").asText());
        byte[] nonce = scheme >= 0x40
            ? MqttSn2NonceDeriver.derive(prefix, scheme <= 0x45 ? 13 : 12)
            : new byte[0];
        if (scheme >= 0x40) {
          assertArrayEquals(HexFormat.of().parseHex(vector.get("nonce").asText()),
              nonce, "Reference client nonce mismatch for scheme " + scheme);
        }
        String algorithm = switch (scheme) {
          case 0 -> "HmacSHA256";
          case 1 -> "HmacSHA3-256";
          case 0x49 -> "ChaCha20";
          default -> "AES";
        };
        var result = provider.protect(scheme,
            new SecretKeySpec(keyBytes, algorithm), nonce, prefix, plaintext);
        assertArrayEquals(HexFormat.of().parseHex(vector.get("protected").asText()),
            result.protectedBytes(), "Client ciphertext mismatch scheme " + scheme);
        assertArrayEquals(HexFormat.of().parseHex(vector.get("tag").asText()),
            result.tag(), "Client authentication tag mismatch scheme " + scheme);
        assertArrayEquals(plaintext, provider.unprotect(scheme,
            new SecretKeySpec(keyBytes, algorithm), nonce, prefix, result));
        checked++;
      }
      assertEquals(15, checked, "All CSD01 schemes in client vectors must be checked");
    }
  }
}
