#!/bin/bash

#
#
#  Copyright [ 2020 - 2024 ] Matthew Buckton
#  Copyright [ 2024 - 2025 ] MapsMessaging B.V.
#
#  Licensed under the Apache License, Version 2.0 with the Commons Clause
#  (the "License"); you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at:
#
#      http://www.apache.org/licenses/LICENSE-2.0
#      https://commonsclause.com/
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

PID_FILE="/opt/maps/pid"

start() {
    echo "Starting maps..."
    nohup /opt/maps/bin/start.sh > /var/log/maps/maps.log 2>&1 &
}

stop() {
    echo "Stopping maps..."
    if [ -f "$PID_FILE" ]; then
        PID=$(cat $PID_FILE)
        if [ -n "$PID" ]; then
            kill $PID
            echo "maps stopped"
        else
            echo "PID file is empty"
        fi
        rm -f $PID_FILE
    else
        echo "PID file not found"
    fi
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
