#!/bin/bash

#
# Copyright [ 2020 - 2024 ] [Matthew Buckton]
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

PID_FILE="/opt/message_daemon/pid"

start() {
    echo "Starting message-daemon..."
    /opt/message_daemon/bin/start.sh
}

stop() {
    echo "Stopping message-daemon..."
    if [ -f "$PID_FILE" ]; then
        PID=$(cat $PID_FILE)
        if [ -n "$PID" ]; then
            kill $PID
            echo "message-daemon stopped"
        else
            echo "PID file is empty"
        fi
        rm -f $PID_FILE
    else
        echo "PID file not found"
    fi
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
