name: Automerge Dependabot PRs

on: pull_request

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.title, 'AWS')
    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@v0.14.3
        with:
          mergeMethod: squash
          commitMessageTemplate: "chore(dependencies): update dependencies"
          token: ${{ secrets.GITHUB_TOKEN }}
