name: Automerge Dependabot PRs

on:
  pull_request:
    branches:
      - development

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.title, 'AWS')
    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@v0.14.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          commit-message-template: "chore(dependencies): update dependencies"
